name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - 'README.md'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Copy kelkkareitit pmtiles
        run: cp kelkkareitit-v5/data/kelkkareitit.pmtiles.gz kelkkareitit-v5/frontend/kelkkareitit.pmtiles.gz
      - name: List files
        run: ls -laR kelkkareitit-v5/frontend

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'kelkkareitit-v5/frontend/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

